import { parseYaml } from 'obsidian'

export const FRONTMATTER_KEY = 'pm-project'
export const TASK_FRONTMATTER_KEY = 'pm-task'
export const COLLECTION_FRONTMATTER_KEY = 'pm-collection'
/** Marks a project note as a programme: it groups projects and holds no work itself. */
export const PROGRAM_FRONTMATTER_KEY = 'pm-program'

export function parseFrontmatter(content: string): {
  frontmatter: Record<string, unknown> | null
  body: string
} {
  if (!content.startsWith('---')) return { frontmatter: null, body: content }
  const end = content.indexOf('\n---', 4)
  if (end === -1) return { frontmatter: null, body: content }
  const raw = content.slice(4, end)
  const body = content.slice(end + 4).trim()
  try {
    return { frontmatter: parseYaml(raw) as Record<string, unknown>, body }
  } catch {
    return { frontmatter: null, body: content }
  }
}

/** Without this the generated wiki-link lines would be duplicated on every save. */
export function stripAutoGeneratedContent(body: string): string {
  let result = body
  result = result.replace(/^Project: \[\[.*\]\]$/gm, '')
  result = result.replace(/^Parent: \[\[.*\]\]$/gm, '')
  result = result.replace(/\n## Subtasks[\s\S]*$/, '')
  result = result.replace(/\n## Document[\s\S]*$/, '')
  return result.trim()
}

/** Handles strings, numbers, booleans, arrays, and objects. Nothing else. */
export function appendYaml(lines: string[], obj: Record<string, unknown>, indent: number): void {
  const pad = '  '.repeat(indent)
  for (const [key, val] of Object.entries(obj)) {
    if (val === null || val === undefined) {
      lines.push(`${pad}${key}:`)
    } else if (typeof val === 'boolean') {
      lines.push(`${pad}${key}: ${val}`)
    } else if (typeof val === 'number') {
      lines.push(`${pad}${key}: ${val}`)
    } else if (typeof val === 'string') {
      const escaped = val.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')
      lines.push(`${pad}${key}: "${escaped}"`)
    } else if (Array.isArray(val)) {
      if (val.length === 0) {
        lines.push(`${pad}${key}: []`)
      } else if (typeof val[0] === 'object') {
        lines.push(`${pad}${key}:`)
        for (const item of val) {
          const entries = Object.entries(item as Record<string, unknown>)
          if (entries.length === 0) continue
          const [firstKey, firstVal] = entries[0]
          lines.push(`${pad}  - ${firstKey}: ${JSON.stringify(firstVal)}`)
          for (const [k, v] of entries.slice(1)) {
            lines.push(`${pad}    ${k}: ${JSON.stringify(v)}`)
          }
        }
      } else {
        const items = val.map((v) => JSON.stringify(v)).join(', ')
        lines.push(`${pad}${key}: [${items}]`)
      }
    } else if (typeof val === 'object') {
      const keys = Object.keys(val)
      if (keys.length === 0) {
        lines.push(`${pad}${key}: {}`)
      } else {
        lines.push(`${pad}${key}:`)
        appendYaml(lines, val as Record<string, unknown>, indent + 1)
      }
    }
  }
}

export function isOldFormat(frontmatter: Record<string, unknown>): boolean {
  return Array.isArray(frontmatter.tasks) && frontmatter.tasks.length > 0 && !Array.isArray(frontmatter.taskIds)
}

/** A line the task list generator produced: "- [ ] [[note|Title]]". */
const GENERATED_TASK_LINE = /^-\s\[[ xX]\]\s/

/** Guards against cutting a "## Tasks" heading the user wrote themselves. */
function isGeneratedTaskList(section: string): boolean {
  const lines = section.split('\n').filter((line) => line.trim() !== '')
  return lines.length > 0 && lines.every((line) => GENERATED_TASK_LINE.test(line.trim()))
}

/** Cuts the generated "## Tasks" list, which serializeProject always writes last. */
export function stripGeneratedTaskList(body: string): string {
  const lines = body.split('\n')
  let start = -1
  for (let i = lines.length - 1; i >= 0; i--) {
    if (lines[i].trim() === '## Tasks') {
      start = i
      break
    }
  }
  if (start === -1) return body
  if (!isGeneratedTaskList(lines.slice(start + 1).join('\n'))) return body
  return lines.slice(0, start).join('\n')
}

/**
 * What is left of a project note's body once the plugin's own output — the title
 * heading, the description echo and the task list — is taken out. Whatever remains
 * the user typed by hand, so the next save has to write it back.
 *
 * Matching the description exactly means a body we did not write falls through
 * untouched: the worst case is that it is kept twice, never that it is dropped.
 */
export function projectBodyRemainder(body: string, icon: string, title: string, description: string): string {
  let rest = stripGeneratedTaskList(body).trim()
  const desc = description.trim()
  const takeDescription = (): void => {
    if (desc && rest.startsWith(desc)) rest = rest.slice(desc.length).trim()
  }
  // Before the heading too: a hand-made note's whole body is its description.
  takeDescription()
  const heading = `# ${icon} ${title}`.trim()
  if (rest.startsWith(heading)) rest = rest.slice(heading.length).trim()
  takeDescription()
  return rest
}
