import type {
  Collection,
  CustomFieldDef,
  DependencyOption,
  DocApproval,
  DocumentMeta,
  DocVersion,
  FilterState,
  PriorityConfig,
  PriorityIconSet,
  Project,
  ProjectConfig,
  SavedView,
  StatusConfig,
  Task,
  ViewMode
} from '../types'
import {
  CUSTOM_FIELD_TYPES,
  DEPENDENCY_TYPES,
  DOC_STATES,
  makeDocument,
  makeTask,
  PRIORITY_ICON_SETS,
  VIEW_MODES
} from '../types'
import { PROGRAM_FRONTMATTER_KEY, stripAutoGeneratedContent } from './YamlParser'

/**
 * Frontmatter is hand-editable, so a list of names or ids can hold anything YAML allows.
 * Numbers are kept as their text; a mapping or a null has no name to show and is dropped.
 */
export function stringList(raw: unknown): string[] {
  if (!Array.isArray(raw)) return []
  const values: string[] = []
  for (const entry of raw) {
    if (typeof entry === 'string') {
      if (entry.trim()) values.push(entry)
    } else if (typeof entry === 'number' && Number.isFinite(entry)) values.push(String(entry))
  }
  return values
}

/** Entries without a usable id are dropped; a bad type falls back to free text. */
export function customFieldList(raw: unknown): CustomFieldDef[] {
  if (!Array.isArray(raw)) return []
  const fields: CustomFieldDef[] = []
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue
    const f = entry as Partial<CustomFieldDef>
    if (typeof f.id !== 'string' || !f.id) continue
    const field: CustomFieldDef = {
      id: f.id,
      name: typeof f.name === 'string' ? f.name : f.id,
      type: CUSTOM_FIELD_TYPES.includes(f.type as CustomFieldDef['type']) ? (f.type as CustomFieldDef['type']) : 'text'
    }
    const options = stringList(f.options)
    if (options.length) field.options = options
    if (typeof f.icon === 'string' && f.icon) field.icon = f.icon
    fields.push(field)
  }
  return fields
}

export function hydrateSavedViews(raw: unknown[]): SavedView[] {
  if (!Array.isArray(raw)) return []
  return raw
    .filter((r) => r && typeof r === 'object')
    .map((r) => {
      const v = r as Record<string, unknown>
      const filter = (v.filter ?? {}) as Record<string, unknown>
      const viewMode = v.viewMode
      // Matched against the list rather than spelled out again: a view added later is
      // recognised here without anyone having to remember this line.
      const validViewMode: ViewMode | undefined = VIEW_MODES.find((mode) => mode === viewMode)
      return {
        id: (v.id as string) ?? '',
        name: (v.name as string) ?? 'Untitled',
        filter: {
          text: (filter.text as string) ?? '',
          statuses: Array.isArray(filter.statuses) ? filter.statuses : [],
          priorities: Array.isArray(filter.priorities) ? filter.priorities : [],
          assignees: Array.isArray(filter.assignees) ? filter.assignees : [],
          tags: Array.isArray(filter.tags) ? filter.tags : [],
          dueDateFilter: (filter.dueDateFilter as string as SavedView['filter']['dueDateFilter']) ?? 'any',
          showArchived: (filter.showArchived as boolean) ?? false
        },
        sortKey: (v.sortKey as string) ?? 'status',
        sortDir: (v.sortDir as 'asc' | 'desc') ?? 'asc',
        ...(validViewMode ? { viewMode: validViewMode } : {})
      }
    })
}

/** The documentary block, defaulted field by field: a note edited by hand is still read. */
function readDocument(raw: unknown): DocumentMeta | undefined {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return undefined
  const r = raw as Record<string, unknown>
  const state = DOC_STATES.find((known: string) => known === r.state) ?? 'expected'
  return makeDocument({
    state,
    file: typeof r.file === 'string' ? r.file : '',
    linked: r.linked === true,
    reference: typeof r.reference === 'string' ? r.reference : '',
    issue: typeof r.issue === 'string' ? r.issue : '',
    issuer: typeof r.issuer === 'string' ? r.issuer : '',
    recipient: typeof r.recipient === 'string' ? r.recipient : '',
    phase: typeof r.phase === 'string' ? r.phase : '',
    approvers: stringList(r.approvers),
    approvals: Array.isArray(r.approvals)
      ? (r.approvals as DocApproval[]).map((entry) => ({
          by: String(entry?.by ?? ''),
          at: String(entry?.at ?? ''),
          verdict: entry?.verdict === 'rejected' ? 'rejected' : 'approved',
          note: String(entry?.note ?? '')
        }))
      : [],
    versions: Array.isArray(r.versions)
      ? (r.versions as DocVersion[])
          .map((entry, i) => ({
            version: typeof entry?.version === 'number' ? entry.version : i + 1,
            file: String(entry?.file ?? ''),
            at: String(entry?.at ?? ''),
            by: String(entry?.by ?? ''),
            note: String(entry?.note ?? '')
          }))
          .sort((a, b) => a.version - b.version)
      : []
  })
}

/** An unknown type reads as a plain task rather than breaking the note. */
function readType(raw: unknown): Task['type'] {
  return raw === 'milestone' || raw === 'subtask' || raw === 'phase' || raw === 'document' ? raw : 'task'
}

export function mapRawToTask(r: Record<string, unknown>, overrides?: Partial<Task>): Task {
  return makeTask({
    id: r.id as string,
    title: (r.title as string) ?? 'Untitled',
    description: (r.description as string) ?? '',
    type: readType(r.type),
    status: (r.status as Task['status']) ?? 'todo',
    priority: (r.priority as Task['priority']) ?? 'medium',
    start: (r.start as string) ?? '',
    due: (r.due as string) ?? '',
    progress: typeof r.progress === 'number' ? r.progress : 0,
    completed: (r.completed as string) ?? '',
    // On the metadataCache path `r` is Obsidian's live frontmatter object, so these
    // containers are copied, not aliased: sharing them would let an edit corrupt the cache.
    assignees: stringList(r.assignees),
    tags: stringList(r.tags),
    subtasks: [],
    dependencies: stringList(r.dependencies),
    dependencyOptions: dependencyOptionMap(r.dependencyOptions),
    recurrence:
      r.recurrence && typeof r.recurrence === 'object'
        ? ({ ...(r.recurrence as Task['recurrence']) } as Task['recurrence'])
        : undefined,
    timeEstimate: typeof r.timeEstimate === 'number' ? r.timeEstimate : undefined,
    timeLogs: Array.isArray(r.timeLogs)
      ? (r.timeLogs as { date: string; hours: number; note: string }[]).map((log) => ({ ...log }))
      : undefined,
    customFields:
      typeof r.customFields === 'object' && r.customFields !== null
        ? { ...(r.customFields as Record<string, unknown>) }
        : {},
    document: readDocument(r.document),
    collapsed: r.collapsed === true,
    createdAt: (r.createdAt as string) ?? new Date().toISOString(),
    updatedAt: (r.updatedAt as string) ?? new Date().toISOString(),
    ...overrides
  })
}

export function hydrateTasks(raw: unknown[]): Task[] {
  if (!Array.isArray(raw)) return []
  return raw.map((r) => {
    const rec = r as Record<string, unknown>
    return mapRawToTask(rec, {
      subtasks: Array.isArray(rec.subtasks) ? hydrateTasks(rec.subtasks as unknown[]) : []
    })
  })
}

export function hydrateTaskFromFile(
  frontmatter: Record<string, unknown>,
  body: string,
  filePath: string
): { task: Task; subtaskIds: string[]; parentId: string | null } {
  const task = mapRawToTask(frontmatter, {
    description: stripAutoGeneratedContent(body),
    filePath
  })
  const subtaskIds = stringList(frontmatter.subtaskIds)
  const parentId = typeof frontmatter.parentId === 'string' && frontmatter.parentId ? frontmatter.parentId : null
  return { task, subtaskIds, parentId }
}

export function hydrateProjectFromFrontmatter(
  frontmatter: Record<string, unknown>,
  body: string,
  filePath: string,
  basename: string
): Project {
  return {
    id: (frontmatter.id as string) ?? basename,
    title: (frontmatter.title as string) ?? basename,
    description: (frontmatter.description as string) ?? body.trim(),
    color: (frontmatter.color as string) ?? '#8b72be',
    icon: (frontmatter.icon as string) ?? '\u{1F4CB}',
    tasks: [],
    customFields: customFieldList(frontmatter.customFields),
    teamMembers: stringList(frontmatter.teamMembers),
    createdAt: (frontmatter.createdAt as string) ?? new Date().toISOString(),
    updatedAt: (frontmatter.updatedAt as string) ?? new Date().toISOString(),
    filePath,
    savedViews: hydrateSavedViews((frontmatter.savedViews as unknown[]) ?? []),
    config: hydrateProjectConfig(frontmatter.config),
    // Only when it is one, so a plain project carries no field saying it is not.
    ...(frontmatter[PROGRAM_FRONTMATTER_KEY] === true ? { program: true } : {}),
    taskIndex: new Map()
  }
}

/** Drops malformed fields. Absent or empty means inherit everything. */
function hydrateProjectConfig(raw: unknown): ProjectConfig | undefined {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return undefined
  const r = raw as Record<string, unknown>
  const config: ProjectConfig = {}
  const statuses = hydrateStatusList(r.statuses)
  if (statuses) config.statuses = statuses
  const priorities = hydratePriorityList(r.priorities)
  if (priorities) config.priorities = priorities
  if (typeof r.priorityIcons === 'string' && r.priorityIcons in PRIORITY_ICON_SETS) {
    config.priorityIcons = r.priorityIcons as PriorityIconSet
  }
  const hidden = stringList(r.hiddenCustomFields)
  if (hidden.length) config.hiddenCustomFields = hidden
  if (r.defaultView === 'table' || r.defaultView === 'gantt' || r.defaultView === 'kanban') {
    config.defaultView = r.defaultView
  }
  if (typeof r.autoSchedule === 'boolean') config.autoSchedule = r.autoSchedule
  if (typeof r.pullForwardOnEarlyFinish === 'boolean') config.pullForwardOnEarlyFinish = r.pullForwardOnEarlyFinish
  if (typeof r.respectWorkingDays === 'boolean') config.respectWorkingDays = r.respectWorkingDays
  if (typeof r.autoArchiveDays === 'number' && Number.isFinite(r.autoArchiveDays) && r.autoArchiveDays >= 0) {
    config.autoArchiveDays = Math.floor(r.autoArchiveDays)
  }
  if (typeof r.showSubtreeConnections === 'boolean') config.showSubtreeConnections = r.showSubtreeConnections
  if (
    r.lineBorders === 'none' ||
    r.lineBorders === 'horizontal' ||
    r.lineBorders === 'vertical' ||
    r.lineBorders === 'both'
  ) {
    config.lineBorders = r.lineBorders
  }
  if (typeof r.kanbanShowSubtasks === 'boolean') config.kanbanShowSubtasks = r.kanbanShowSubtasks
  if (typeof r.kanbanShowDescriptionPreview === 'boolean') {
    config.kanbanShowDescriptionPreview = r.kanbanShowDescriptionPreview
  }
  return Object.keys(config).length ? config : undefined
}

function hydrateStatusList(raw: unknown): StatusConfig[] | undefined {
  if (!Array.isArray(raw)) return undefined
  const statuses: StatusConfig[] = []
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue
    const s = entry as Partial<StatusConfig>
    if (typeof s.id !== 'string' || !s.id) continue
    statuses.push({
      id: s.id,
      label: typeof s.label === 'string' ? s.label : s.id,
      color: typeof s.color === 'string' ? s.color : '#8a94a0',
      icon: typeof s.icon === 'string' ? s.icon : '',
      complete: s.complete === true
    })
  }
  return statuses.length ? statuses : undefined
}

function hydratePriorityList(raw: unknown): PriorityConfig[] | undefined {
  if (!Array.isArray(raw)) return undefined
  const priorities: PriorityConfig[] = []
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue
    const p = entry as Partial<PriorityConfig>
    if (typeof p.id !== 'string' || !p.id) continue
    priorities.push({
      id: p.id,
      label: typeof p.label === 'string' ? p.label : p.id,
      color: typeof p.color === 'string' ? p.color : '#8a94a0',
      icon: typeof p.icon === 'string' ? p.icon : ''
    })
  }
  return priorities.length ? priorities : undefined
}

/** Drops entries that name an unknown link type or a lag that is not a finite number. */
function dependencyOptionMap(raw: unknown): Record<string, DependencyOption> | undefined {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return undefined
  const out: Record<string, DependencyOption> = {}
  for (const [id, value] of Object.entries(raw as Record<string, unknown>)) {
    if (!value || typeof value !== 'object') continue
    const entry = value as Record<string, unknown>
    const type = DEPENDENCY_TYPES.find((t) => t === entry.type)
    if (!type) continue
    const lag = typeof entry.lag === 'number' && Number.isFinite(entry.lag) ? Math.trunc(entry.lag) : 0
    out[id] = { type, lag }
  }
  return Object.keys(out).length ? out : undefined
}

/** Shared by saved views and collection rules; unknown fields fall back to a neutral filter. */
function hydrateFilterState(raw: unknown): FilterState {
  const f = (raw && typeof raw === 'object' ? raw : {}) as Record<string, unknown>
  return {
    text: typeof f.text === 'string' ? f.text : '',
    statuses: stringList(f.statuses),
    priorities: stringList(f.priorities),
    assignees: stringList(f.assignees),
    tags: stringList(f.tags),
    dueDateFilter: (typeof f.dueDateFilter === 'string' ? f.dueDateFilter : 'any') as FilterState['dueDateFilter'],
    showArchived: f.showArchived === true
  }
}

/**
 * A collection note. `include`, `exclude` and `sources` are written as wikilinks, so
 * the caller passes the resolver that turns those back into ids and paths.
 */
export function hydrateCollection(
  frontmatter: Record<string, unknown>,
  body: string,
  filePath: string,
  basename: string,
  resolve: { taskId: (raw: string) => string; projectPath: (raw: string) => string | null }
): Collection {
  const description = frontmatter.description
  return {
    id: (frontmatter.id as string) ?? basename,
    title: (frontmatter.title as string) ?? basename,
    description: typeof description === 'string' ? description : body.trim(),
    color: (frontmatter.color as string) ?? '#6b8fbe',
    icon: (frontmatter.icon as string) ?? '\u{1F5C2}️',
    sources: stringList(frontmatter.sources)
      .map(resolve.projectPath)
      .filter((path): path is string => path !== null),
    // Absent, not empty: a collection with no rule is a hand-picked list, which is not
    // the same thing as a rule that matches everything.
    ...(frontmatter.rule ? { rule: hydrateFilterState(frontmatter.rule) } : {}),
    include: stringList(frontmatter.include).map(resolve.taskId),
    exclude: stringList(frontmatter.exclude).map(resolve.taskId),
    createdAt: (frontmatter.createdAt as string) ?? new Date().toISOString(),
    updatedAt: (frontmatter.updatedAt as string) ?? new Date().toISOString(),
    filePath
  }
}
