import { normalizePath, stringifyYaml } from 'obsidian'
import {
  DEFAULT_DEPENDENCY_OPTION,
  type Collection,
  type DependencyOption,
  type Project,
  type ProjectConfig,
  type StatusConfig,
  type DocumentMeta,
  type Task
} from '../types'
import { isTerminalStatus, sanitizeFileName } from '../utils'
import {
  appendYaml,
  COLLECTION_FRONTMATTER_KEY,
  FRONTMATTER_KEY,
  stripAutoGeneratedContent,
  TASK_FRONTMATTER_KEY
} from './YamlParser'

/** Writes the wikilinks a note holds, abbreviated against that note's own location. */
export interface RefWriter {
  link(targetPath: string, title: string): string
  /** Null when no note in the vault holds that task id. */
  dependency(taskId: string): string | null
}

export const PROJECT_FRONTMATTER_KEYS: ReadonlySet<string> = new Set([
  FRONTMATTER_KEY,
  'id',
  'title',
  'description',
  'color',
  'icon',
  'taskIds',
  'parent',
  'customFields',
  'teamMembers',
  'savedViews',
  'createdAt',
  'updatedAt',
  'config',
  'tasks'
])

export const TASK_FRONTMATTER_KEYS: ReadonlySet<string> = new Set([
  TASK_FRONTMATTER_KEY,
  'projectId',
  'parentId',
  'id',
  'title',
  'description',
  'type',
  'status',
  'priority',
  'start',
  'due',
  'progress',
  'assignees',
  'tags',
  'subtaskIds',
  'dependencies',
  'dependencyOptions',
  'createdAt',
  'updatedAt',
  'completed',
  'recurrence',
  'timeEstimate',
  'timeLogs',
  'customFields',
  'document',
  'collapsed'
])

export const COLLECTION_FRONTMATTER_KEYS: ReadonlySet<string> = new Set([
  COLLECTION_FRONTMATTER_KEY,
  'id',
  'title',
  'description',
  'color',
  'icon',
  'sources',
  'rule',
  'include',
  'exclude',
  'createdAt',
  'updatedAt'
])

export function foreignFrontmatter(
  frontmatter: Record<string, unknown> | null,
  owned: ReadonlySet<string>
): Record<string, unknown> {
  const out: Record<string, unknown> = {}
  if (!frontmatter) return out
  for (const [key, value] of Object.entries(frontmatter)) {
    if (!owned.has(key)) out[key] = value
  }
  return out
}

function appendForeignYaml(lines: string[], foreign: Record<string, unknown>): void {
  if (Object.keys(foreign).length) lines.push(stringifyYaml(foreign).trimEnd())
}

/** Only fields the project actually overrides; an empty block is omitted entirely. */
function serializeProjectConfig(config: ProjectConfig | undefined): Record<string, unknown> | null {
  if (!config) return null
  const out: Record<string, unknown> = {}
  if (config.statuses?.length) out.statuses = config.statuses
  if (config.priorities?.length) out.priorities = config.priorities
  if (config.priorityIcons) out.priorityIcons = config.priorityIcons
  if (config.hiddenCustomFields?.length) out.hiddenCustomFields = config.hiddenCustomFields
  if (config.defaultView) out.defaultView = config.defaultView
  if (config.autoSchedule !== undefined) out.autoSchedule = config.autoSchedule
  if (config.pullForwardOnEarlyFinish !== undefined) out.pullForwardOnEarlyFinish = config.pullForwardOnEarlyFinish
  if (config.respectWorkingDays !== undefined) out.respectWorkingDays = config.respectWorkingDays
  if (config.autoArchiveDays !== undefined) out.autoArchiveDays = config.autoArchiveDays
  if (config.showSubtreeConnections !== undefined) out.showSubtreeConnections = config.showSubtreeConnections
  if (config.lineBorders) out.lineBorders = config.lineBorders
  if (config.kanbanShowSubtasks !== undefined) out.kanbanShowSubtasks = config.kanbanShowSubtasks
  if (config.kanbanShowDescriptionPreview !== undefined) {
    out.kanbanShowDescriptionPreview = config.kanbanShowDescriptionPreview
  }
  return Object.keys(out).length ? out : null
}

export function serializeProject(
  project: Project,
  statuses: StatusConfig[],
  refs: RefWriter,
  foreign: Record<string, unknown> = {},
  /** Body the user wrote by hand, from projectBodyRemainder. Kept above the task list. */
  extraBody = ''
): string {
  const seen = new Set<string>()
  const tasks: Task[] = []
  for (const t of project.tasks) {
    if (seen.has(t.id)) continue
    seen.add(t.id)
    tasks.push(t)
  }
  const taskIds = tasks.map((t) => (t.filePath ? refs.link(t.filePath, t.title) : t.id))

  const fm: Record<string, unknown> = {
    [FRONTMATTER_KEY]: true,
    id: project.id,
    title: project.title,
    description: project.description,
    color: project.color,
    icon: project.icon,
    taskIds,
    ...(project.parentPath ? { parent: `[[${project.parentPath.replace(/\.md$/, '')}]]` } : {}),
    customFields: project.customFields,
    teamMembers: project.teamMembers,
    savedViews: project.savedViews.length ? project.savedViews : [],
    createdAt: project.createdAt,
    updatedAt: project.updatedAt
  }
  const config = serializeProjectConfig(project.config)
  if (config) fm.config = config

  const yamlLines: string[] = ['---']
  appendYaml(yamlLines, fm, 0)
  appendForeignYaml(yamlLines, foreign)
  yamlLines.push('---')
  yamlLines.push('')
  yamlLines.push(`# ${project.icon} ${project.title}`)
  yamlLines.push('')
  if (project.description) {
    yamlLines.push(project.description)
    yamlLines.push('')
  }
  // Above the task list, which has to stay last for projectBodyRemainder to find it.
  if (extraBody.trim()) {
    yamlLines.push(extraBody.trim())
    yamlLines.push('')
  }
  if (tasks.length) {
    yamlLines.push('## Tasks')
    for (const t of tasks) {
      if (t.filePath) {
        const check = isTerminalStatus(t.status, statuses) ? 'x' : ' '
        yamlLines.push(`- [${check}] ${refs.link(t.filePath, t.title)}`)
      }
    }
    yamlLines.push('')
  }

  return yamlLines.join('\n')
}

export function buildTaskFrontmatter(
  task: Task,
  project: Project,
  parentTask: Task | null,
  refs: RefWriter
): Record<string, unknown> {
  const fm: Record<string, unknown> = {
    [TASK_FRONTMATTER_KEY]: true,
    projectId: refs.link(project.filePath, project.title),
    parentId: parentTask?.filePath ? refs.link(parentTask.filePath, parentTask.title) : (parentTask?.id ?? null),
    id: task.id,
    title: task.title,
    type: task.type,
    status: task.status,
    priority: task.priority,
    start: task.start,
    due: task.due,
    progress: task.progress,
    assignees: task.assignees,
    tags: task.tags,
    subtaskIds: task.subtasks.map((s) => (s.filePath ? refs.link(s.filePath, s.title) : s.id)),
    dependencies: task.dependencies.map((id) => refs.dependency(id) ?? id),
    createdAt: task.createdAt,
    updatedAt: task.updatedAt
  }
  const depOptions = liveDependencyOptions(task)
  if (depOptions) fm.dependencyOptions = depOptions
  if (task.completed) fm.completed = task.completed
  if (task.recurrence) fm.recurrence = task.recurrence
  if (task.timeEstimate !== undefined) fm.timeEstimate = task.timeEstimate
  if (task.timeLogs?.length) fm.timeLogs = task.timeLogs
  if (Object.keys(task.customFields).length) fm.customFields = task.customFields
  const document = serializeDocument(task.document)
  if (document) fm.document = document
  return fm
}

/**
 * Options for predecessors the task still depends on, dropping any left behind by a
 * removed dependency, and any that just restate the finish-to-start default.
 */
function liveDependencyOptions(task: Task): Record<string, DependencyOption> | null {
  if (!task.dependencyOptions) return null
  const live: Record<string, DependencyOption> = {}
  for (const id of task.dependencies) {
    const option = task.dependencyOptions[id]
    if (!option) continue
    if (option.type === DEFAULT_DEPENDENCY_OPTION.type && option.lag === DEFAULT_DEPENDENCY_OPTION.lag) continue
    live[id] = option
  }
  return Object.keys(live).length ? live : null
}

/** The file's own name, which is what a link to it should read as. */
function fileNameOf(path: string): string {
  return path.slice(path.lastIndexOf('/') + 1)
}

/**
 * The documentary block, with anything still empty left out. A document only expected,
 * with nothing filled in yet, then costs its note four lines rather than fifteen.
 */
function serializeDocument(meta: DocumentMeta | undefined): Record<string, unknown> | null {
  if (!meta) return null
  const out: Record<string, unknown> = { state: meta.state }
  if (meta.file) out.file = meta.file
  if (meta.linked) out.linked = true
  for (const key of ['reference', 'issue', 'issuer', 'recipient', 'phase'] as const) {
    if (meta[key]) out[key] = meta[key]
  }
  if (meta.approvers.length) out.approvers = meta.approvers
  if (meta.approvals.length) out.approvals = meta.approvals
  if (meta.versions.length) out.versions = meta.versions
  return out
}

export function serializeTask(
  task: Task,
  project: Project,
  parentTask: Task | null,
  statuses: StatusConfig[],
  refs: RefWriter,
  foreign: Record<string, unknown> = {}
): string {
  const fm = buildTaskFrontmatter(task, project, parentTask, refs)

  const yamlLines: string[] = ['---']
  appendYaml(yamlLines, fm, 0)
  appendForeignYaml(yamlLines, foreign)
  yamlLines.push('---')
  yamlLines.push('')
  const cleanDesc = stripAutoGeneratedContent(task.description)
  if (cleanDesc) {
    yamlLines.push(cleanDesc)
    yamlLines.push('')
  }

  if (parentTask?.filePath) {
    yamlLines.push(`Parent: ${refs.link(parentTask.filePath, parentTask.title)}`)
  } else {
    yamlLines.push(`Project: ${refs.link(project.filePath, project.title)}`)
  }

  if (task.subtasks.length) {
    yamlLines.push('')
    yamlLines.push('## Subtasks')
    for (const sub of task.subtasks) {
      const check = isTerminalStatus(sub.status, statuses) ? 'x' : ' '
      const link = sub.filePath ? refs.link(sub.filePath, sub.title) : `[[${taskSlug(sub.title)}|${sub.title}]]`
      yamlLines.push(`- [${check}] ${link}`)
    }
  }

  // Last, and generated like the section above it: opening the note in Obsidian should
  // reach the file and its history without the plugin having to be running.
  if (task.document) {
    yamlLines.push('')
    yamlLines.push('## Document')
    if (task.document.file) yamlLines.push(refs.link(task.document.file, fileNameOf(task.document.file)))
    for (const version of [...task.document.versions].reverse()) {
      const note = version.note ? ` — ${version.note}` : ''
      yamlLines.push(`- v${version.version} · ${version.at.slice(0, 10)} · ${version.by}${note}`)
    }
  }

  return yamlLines.join('\n')
}

/** Keeps paths under Windows MAX_PATH and the limits mobile and sync impose. */
export const TASK_SLUG_MAX_LENGTH = 60

function taskSlug(title: string): string {
  return sanitizeFileName(title).toLowerCase().replace(/\s+/g, '-').slice(0, TASK_SLUG_MAX_LENGTH)
}

export function taskFilePath(taskTitle: string, folder: string): string {
  return `${folder}/${taskSlug(taskTitle)}.md`
}

/** A project owns a folder named after it, holding its note and its `_tasks/`. */
export function projectFilePath(projectTitle: string, folder: string): string {
  const name = sanitizeFileName(projectTitle)
  return normalizePath(`${folder}/${name}/${name}.md`)
}

/**
 * A collection note holds its definition, not a snapshot of what it currently matches:
 * a rule's members change every time a task anywhere changes, and writing that list to
 * disk would rewrite the note constantly for no gain. The hand-picked entries are
 * written as wikilinks, so Obsidian's backlinks still tie the two together.
 */
export function serializeCollection(
  collection: Collection,
  refs: RefWriter,
  foreign: Record<string, unknown> = {},
  extraBody = ''
): string {
  const fm: Record<string, unknown> = {
    [COLLECTION_FRONTMATTER_KEY]: true,
    id: collection.id,
    title: collection.title,
    description: collection.description,
    color: collection.color,
    icon: collection.icon,
    sources: collection.sources.map((path) => `[[${path.replace(/\.md$/, '')}]]`),
    include: collection.include.map((id) => refs.dependency(id) ?? id),
    exclude: collection.exclude.map((id) => refs.dependency(id) ?? id),
    createdAt: collection.createdAt,
    updatedAt: collection.updatedAt
  }
  if (collection.rule) fm.rule = collection.rule

  const lines: string[] = ['---']
  appendYaml(lines, fm, 0)
  appendForeignYaml(lines, foreign)
  lines.push('---')
  lines.push('')
  lines.push(`# ${collection.icon} ${collection.title}`)
  lines.push('')
  if (collection.description) {
    lines.push(collection.description)
    lines.push('')
  }
  if (extraBody.trim()) {
    lines.push(extraBody.trim())
    lines.push('')
  }
  return lines.join('\n')
}
